### ISSUE TITLE
Replacing adhaan MP3 files

### ISSUE THREAD

**Issue by bamirza** [achaudhry/adhan#4]
I have some custom recorded adhaans that I am trying to swap in place of the pre-determined ones.  I have changed the name of my file to match "Adhan-Makkah.mp3" in /home/pi/adhan but nothing ends up playing.  Is there another folder that I should copy these files to beside that one?

**Comment by achaudhry** [comment]
Salam @bamirza - I'd say instead of replacing it, the easiest thing to do would be to put your files in the adhan folder and update [line 15](https://github.com/achaudhry/adhan/blob/master/updateAzaanTimers.py#L15) (for Fajr) and [line 16](https://github.com/achaudhry/adhan/blob/master/updateAzaanTimers.py#L15) (for the other four) in updateAzaanTimers.py to add you filenames. 

I hope that works for you. Let me know. Thanks!
